server:
  error:
    whitelabel:
      enabled: false
system:
  env: ${spring.profiles.active:default}
  name: ${spring.application.name:Loafer}
  port: ${server.port:8080}
  formatted-version: 0.0.1-SNAPSHOT
spring:
  banner:
    location: classpath:loafer-banner.txt
  task:
    execution:
      pool:
        core-size: 8
        max-size: 64
        keep-alive: 15s
        allow-core-thread-timeout: false
        queue-capacity: 256
      thread-name-prefix: loaf-task-
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      thread-name-prefix: loaf-scheduling
      pool:
        size: 2
      shutdown:
        await-termination: true
        await-termination-period: 30s